name: Moim
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.2.0
  google_sign_in: ^4.0.11
  http: ^0.12.0+2
  firebase_auth: ^0.14.0+5
  provider: ^3.1.0+1
  shared_preferences: ^0.5.3+4
  logger: ^0.7.0+2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.3"
  flutter_native_splash: ^0.1.9

flutter_icons:
  android: true
  ios: true
  image_path: 'icon/icon.png'
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  
  assets:
    - images/icons8-tree-64.png
    - images/study.jpg
  fonts:
    - family: BMHANNA
      fonts:
        - asset: fonts/BMHANNAPro.ttf
    - family: BlackHanSans
      fonts:
        - asset: fonts/BlackHanSans-Regular.ttf

flutter_native_splash:
  image: icon/ic_launcher.png
  color: "F3FBC5"